Importing the necessary modules for processing the multi-dimensional data

In [ ]:
import pandas as pd

In [ ]:
inp = pd.read_csv('/content/drive/MyDrive/Processed_Stemming_Lemmatization.csv')

In [ ]:
inp.head(2)

Unnamed: 0                                              Tweet  \
0           0  Covid-19: Free booster for 18-59 age bracket s...   
1           1  Even though you have received a booster vaccin...   

                                 PreProcessed_Tweets Lang  \
0   covid free booster age bracket still maharashtra   en   
1  even though received booster vaccine dont forg...   en   

                                          Translated  \
0   covid free booster age bracket still maharashtra   
1  even though received booster vaccine dont forg...   

                                    Processed_Tweets  Polarity Sentiment  \
0   covid free booster age bracket still maharashtra       0.4  Positive   
1  even though receiv booster vaccin dont forget ...       0.0   Neutral   

         Date  
0  2022-12-30  
1  2022-12-30

Selecting the necessary columns to check for the accuracy of our model

In [ ]:
inp = inp.drop(['Unnamed: 0',	'PreProcessed_Tweets',	'Translated', 'Lang',	'Tweet',	'Date', 'Polarity'], axis='columns')
inp.head()

Processed_Tweets Sentiment
0   covid free booster age bracket still maharashtra  Positive
1  even though receiv booster vaccin dont forget ...   Neutral
2  mrna vaccin rais risk contract covid mrna vacc...   Neutral
3  fact check directorgener say countri give covi...   Neutral
4  see cdc websit do pfizer updat covid booster a...  Negative

In [ ]:
# inp.to_csv("Processed_Tweets.csv")

In [ ]:
inp.isna().sum()
inp = inp.dropna()

In [ ]:
X= inp['Processed_Tweets']
y = inp['Sentiment']

Splitting the dataset into training and testing datasets

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

In [ ]:
X_train.shape

(144971,)

Convert the processed texts into vectors in order to check the accuracy of our model

In [ ]:
# from sklearn.feature_extraction.text import CountVectorizer
# count_vect=CountVectorizer()
# X_train_counts =count_vect.fit_transform(X_train)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
count_vect = TfidfVectorizer(analyzer='word',stop_words= 'english')
X_train_counts = count_vect.fit_transform(X_train)

In [ ]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidf_transformer = TfidfTransformer()
X_train_tfidf = tfidf_transformer.fit_transform(X_train_counts)

In [ ]:
X_train_tfidf.shape

(144971, 40658)

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC

text_clf = Pipeline([('tfidf', TfidfVectorizer()),
                     ('clf', SVC()),])
text_clf.fit(X_train, y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('clf', SVC())])

In [ ]:
predictions = text_clf.predict(X_test)

In [ ]:
from sklearn import metrics
cf_matrix = metrics.confusion_matrix(y_test,predictions)
print(cf_matrix)

[[ 7459   271   373]
 [  113 28495    82]
 [  300   188 24850]]


In [ ]:
print(metrics.classification_report(y_test,predictions))

              precision    recall  f1-score   support

    Negative       0.95      0.92      0.93      8103
     Neutral       0.98      0.99      0.99     28690
    Positive       0.98      0.98      0.98     25338

    accuracy                           0.98     62131
   macro avg       0.97      0.96      0.97     62131
weighted avg       0.98      0.98      0.98     62131



In [ ]:
print(metrics.accuracy_score(y_test,predictions))

0.9786419017881572


In [ ]:
print(metrics.precision_score(y_test,predictions,average='macro'))

0.9712340669827323


In [ ]:
print(metrics.f1_score(y_test,predictions,average='macro'))

0.9679560253277364


In [ ]:
print(metrics.recall_score(y_test,predictions,average='macro'))

0.9648222865364716
